258 utility to post process hhrs to generate bar chart needed for playbook
IN-CORE/pyincore pull request #260
Opened 2023-01-27 15:48 UTC by longshuicy

here is the utility function to parse HHRS to json to be used in the barchart

2023-01-27 15:56 UTC, nunezco2 approved these changes

2023-01-31 19:37 UTC, navarroc commented
Can you fix the spelling of hhrsoutputprocess.py? It's currently spelled hhrsouptutprocess.py

2023-01-31 20:07 UTC, nunezco2 requested changes

2023-01-31 20:07 UTC, nunezco2 commented on pyincore/utils/hhrsoutputprocess.py
> +class HHRSOutputPRocess:
HHRSOutputPRocess -> HHRSOutputProcess

2023-01-31 20:07 UTC, nunezco2 commented on tests/pyincore/analyses/housingrecoveryserial/test_housingrecoverysequential.py
> +from pyincore import IncoreClient, FragilityService, MappingSet, HHRSOutputPRocess
HHRSOutputPRocess -> HHRSOutputProcess

2023-01-31 20:44 UTC, nunezco2 approved these changes

2023-01-31 20:46 UTC, navarroc approved these changes

2023-01-31 20:48 UTC, merged