32 epfdamage liquefaction and LS name fixes.
IN-CORE/pyincore pull request #50
Opened 2021-11-22 20:43 UTC by vnarah2

See the #32 for more details of the task. It handles the below:
1. Fix the broken liquefaction logic on EPF Damage
2. Add test for liquefaction, remove "refactored" test because they are not needed any more
3. Remove deprecated LS/DS name specific method
4. Use 10 digit precision when adjusting PGD limit states

Use the test_epfddamage.py to test

2021-11-22 21:10 UTC, vnarah2 commented
@ncsa-mo we need to create an issue to update the documentation related to these spec changes (liquefaction_fragility_key addition etc.) . Here: https://incore-dev.ncsa.illinois.edu/doc/incore/analyses/epf_dmg.html

2021-11-30 19:35 UTC, navarroc requested changes
Unused import on line 7, unused variables around line 57, extra space on line 290

2021-11-30 19:35 UTC, navarroc commented
Other than the few cosmetic things, this change looks good and I tested it with a notebook I had for epf_damage and verified with/without liquefaction works, setting the liquefaction key works as well.

2021-11-30 19:36 UTC, navarroc commented
We probably need to update the documentation to include the new liq_fragility_key.

2021-12-02 00:09 UTC, longshuicy approved these changes
LGTM approving

2021-12-03 15:16 UTC, navarroc commented on pyincore/analyses/epfdamage/epfdamage.py
>          #############################################################
Leftover comment line can probably be removed

2021-12-03 15:17 UTC, navarroc approved these changes
Besides the empty comment line, this looks good, approving

2021-12-03 18:10 UTC, merged