61 fix docker build for docs
IN-CORE/pyincore pull request #62
Opened 2021-12-13 19:21 UTC by ywkim312

Added env variable for PATH to docker file for pyincore build docker

2021-12-13 21:39 UTC, ywkim312 commented
Alternative way could be like from `RUN sphinx-build -v -b html docs/source docs/build` to `RUN /full/path/sphinx-build -v -b html docs/source docs/build`

2021-12-14 05:38 UTC, robkooper requested changes
small change

2021-12-14 05:38 UTC, robkooper commented on CHANGELOG.md
> +- Automatic build for pyincore documentation docker [#61](https://github.com/IN-CORE/pyincore/issues/61)
add new line

2021-12-14 05:39 UTC, robkooper requested changes

2021-12-14 05:39 UTC, robkooper commented on Dockerfile
> +ENV PATH="/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```suggestion
ENV PATH "$MAMBA_ROOT_PREFIX/bin:$PATH"
```

2021-12-14 15:09 UTC, ywkim312 commented on Dockerfile
> +ENV PATH="/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
changed

2021-12-14 15:10 UTC, ywkim312 commented on CHANGELOG.md
> +- Automatic build for pyincore documentation docker [#61](https://github.com/IN-CORE/pyincore/issues/61)
added

2021-12-14 16:09 UTC, robkooper approved these changes

2021-12-14 16:13 UTC, merged